import Budget from '@App/components/Dashboard/Budget'
import CurrencyMenu from '@App/components/Dashboard/CurrencyMenu'
import CustomBudget from '@App/components/Dashboard/CustomBudget'
import AppHeader from '@App/components/Logged/AppHeader'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'

export interface CurrencyMenuProps {
  selectedCurrency: string
  // eslint-disable-next-line no-unused-vars
  setSelectedCurrency?: (x:string) => void
}

const Dashboard:NextPage = () => {
  const [selectedCurrency, setSelectedCurrency] = useState('USD')

  return (
    <>
      <Head>
        <title>Dashboard - exgPlanner </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <AppHeader />
        <CurrencyMenu selectedCurrency={selectedCurrency} setSelectedCurrency={setSelectedCurrency} />
        <Budget selectedCurrency={selectedCurrency} />
        <CustomBudget selectedCurrency={selectedCurrency} />
      </>
    </>
  )
}

export default Dashboard
