import CurrencyMenu from '@App/components/Dashboard/CurrencyMenu'
import AppHeader from '@App/components/Logged/AppHeader'
import type { NextPage } from 'next'
import Head from 'next/head'

const Dashboard:NextPage = () => {

  return (
    <>
      <Head>
        <title>Dashboard - exgPlanner </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <AppHeader />
        <CurrencyMenu />
        
      </>
    </>
  )
}

export default Dashboard
