import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import ForgotPassword from '@App/components/ForgotPassword'

const Forgot:NextPage = () => {
  return (
    <>
        <Head>
            <title>Forgot password - exgPlanner</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    
        <ForgotPassword />

    </>
  )
}

export default Forgot