import LoginScreen from '@App/components/LoginScreen'
import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>exgPlanner - Your exchange planner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginScreen />
    </>
  )
}

export default Home