import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import RegisterPage from '@App/components/Register'

const Register:NextPage = () => {
  return (
    <>
      <Head>
        <title>Create new account - exgPlanner </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <RegisterPage />

    </>
  )
}

export default Register