import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import InitialAppScreen from '@App/components/InitialAppScreen'


const Start:NextPage = () => {

  const userFilledTheFields = false

  return (
    <>
      <Head>
        <title>Start - exgPlanner </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {userFilledTheFields ? 
        <div>dashboard</div>
        : 
        <InitialAppScreen />
      }
      
    </>
  )
}

export default Start
