import React, { useContext, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { UserContext } from '@App/contexts/User'
import { handleGetUserToken } from '@App/utils/utils'
import AppHeader from '@App/components/Logged/AppHeader'
import { Button } from '@App/components/Button/Button'
import Link from 'next/link'
import styled from 'styled-components'

const Start:NextPage = () => {
  const { user } = useContext(UserContext)
  const { name, email, token } = user


  useEffect(() => {
    if(token) {
      console.log("Logado")
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  
  return (
    <>
        <Head>
            <title>Start - exgPlanner </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <AppStartContainer>
          <AppHeader />
          <AppStartWrapper>

                <WelcomeWrapper>
                  <h2>Welcome to exgPlanner!</h2>

                  <WelcomeMessage>
                      We are here to make your exchange planning easier.
                  </WelcomeMessage>
                  <WelcomeMessage>
                      Let&apos;s start!
                  </WelcomeMessage>

                  <Link href="/start">
                      <Button 
                          as="a"
                          bg='#00BFA6' 
                          fontColor='#FFF' 
                          size={1.4} 
                          margin={'2.5rem 0 2rem'}
                      >
                          Start my travel plan!
                      </Button>
                  </Link>
                  
              </WelcomeWrapper>
          </AppStartWrapper>
        </AppStartContainer>
    </>
  )
}

export default Start

const AppStartContainer = styled.div`
    min-height: 100vh;
`

const AppStartWrapper = styled.div`
    padding: 4rem 2.2rem;
`


const WelcomeWrapper = styled.div`
    h2 {
        font-size: 3rem;
        margin-bottom: 6rem;
        color: #333;
        font-weight: 500;
    }
`
const WelcomeMessage = styled.p`
    margin-bottom: 0.5rem;
`